<?xml version="1.0" encoding="utf-8"?><Database Name="bdownDB" EntityNamespace="BurnDown.Models" ContextNamespace="BurnDown" Class="DB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=bdownDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bdownDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.projects" Member="projects">
    <Type Name="project">
      <Column Name="projectId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="projectName" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="leadDeveloper" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vProjects" Member="vProjects">
    <Type Name="vProject">
      <Column Name="projectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="projectName" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="developerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Developer Name]" Member="Developer_Name" Type="System.String" DbType="NChar(40)" CanBeNull="true" />
      <Column Name="priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.devlopers" Member="devlopers">
    <Type Name="devloper">
      <Column Name="developerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="hoursPerDayAvailable" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vTasks" Member="vTasks">
    <Type Name="vTask">
      <Column Name="taskId" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="assignedTo" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="originalEstimatedHours" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="hoursSpentOnTask" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="project" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="shareOfProject" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="percentCompleted" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="priority" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="taskName" Type="System.String" DbType="NChar(50)" CanBeNull="false" />
      <Column Name="startDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="dueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="hoursForTasksWithHigherPriority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="projectName" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="true" />
      <Column Name="developerId" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="projectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tasks" Member="tasks">
    <Type Name="task">
      <Column Name="taskId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="assignedTo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="originalEstimatedHours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hoursSpentOnTask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="project" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="shareOfProject" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="percentCompleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="taskName" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="startDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dueDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="hoursForTasksWithHigherPriority" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>