//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BurnDown.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class bdownDBEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new bdownDBEntities1 object using the connection string found in the 'bdownDBEntities1' section of the application configuration file.
        /// </summary>
        public bdownDBEntities1() : base("name=bdownDBEntities1", "bdownDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new bdownDBEntities1 object.
        /// </summary>
        public bdownDBEntities1(string connectionString) : base(connectionString, "bdownDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new bdownDBEntities1 object.
        /// </summary>
        public bdownDBEntities1(EntityConnection connection) : base(connection, "bdownDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<agendaItem> agendaItems
        {
            get
            {
                if ((_agendaItems == null))
                {
                    _agendaItems = base.CreateObjectSet<agendaItem>("agendaItems");
                }
                return _agendaItems;
            }
        }
        private ObjectSet<agendaItem> _agendaItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<devloper> devlopers
        {
            get
            {
                if ((_devlopers == null))
                {
                    _devlopers = base.CreateObjectSet<devloper>("devlopers");
                }
                return _devlopers;
            }
        }
        private ObjectSet<devloper> _devlopers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<project> projects
        {
            get
            {
                if ((_projects == null))
                {
                    _projects = base.CreateObjectSet<project>("projects");
                }
                return _projects;
            }
        }
        private ObjectSet<project> _projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<task> tasks
        {
            get
            {
                if ((_tasks == null))
                {
                    _tasks = base.CreateObjectSet<task>("tasks");
                }
                return _tasks;
            }
        }
        private ObjectSet<task> _tasks;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the agendaItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToagendaItems(agendaItem agendaItem)
        {
            base.AddObject("agendaItems", agendaItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the devlopers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodevlopers(devloper devloper)
        {
            base.AddObject("devlopers", devloper);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToprojects(project project)
        {
            base.AddObject("projects", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tasks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotasks(task task)
        {
            base.AddObject("tasks", task);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bdownDBModel", Name="agendaItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class agendaItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new agendaItem object.
        /// </summary>
        /// <param name="agendaItemId">Initial value of the agendaItemId property.</param>
        /// <param name="agendaItemName">Initial value of the agendaItemName property.</param>
        /// <param name="completed">Initial value of the completed property.</param>
        /// <param name="parentTask">Initial value of the parentTask property.</param>
        public static agendaItem CreateagendaItem(global::System.Int32 agendaItemId, global::System.String agendaItemName, global::System.Boolean completed, global::System.Int32 parentTask)
        {
            agendaItem agendaItem = new agendaItem();
            agendaItem.agendaItemId = agendaItemId;
            agendaItem.agendaItemName = agendaItemName;
            agendaItem.completed = completed;
            agendaItem.parentTask = parentTask;
            return agendaItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 agendaItemId
        {
            get
            {
                return _agendaItemId;
            }
            set
            {
                if (_agendaItemId != value)
                {
                    OnagendaItemIdChanging(value);
                    ReportPropertyChanging("agendaItemId");
                    _agendaItemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("agendaItemId");
                    OnagendaItemIdChanged();
                }
            }
        }
        private global::System.Int32 _agendaItemId;
        partial void OnagendaItemIdChanging(global::System.Int32 value);
        partial void OnagendaItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String agendaItemName
        {
            get
            {
                return _agendaItemName;
            }
            set
            {
                OnagendaItemNameChanging(value);
                ReportPropertyChanging("agendaItemName");
                _agendaItemName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("agendaItemName");
                OnagendaItemNameChanged();
            }
        }
        private global::System.String _agendaItemName;
        partial void OnagendaItemNameChanging(global::System.String value);
        partial void OnagendaItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean completed
        {
            get
            {
                return _completed;
            }
            set
            {
                OncompletedChanging(value);
                ReportPropertyChanging("completed");
                _completed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("completed");
                OncompletedChanged();
            }
        }
        private global::System.Boolean _completed;
        partial void OncompletedChanging(global::System.Boolean value);
        partial void OncompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parentTask
        {
            get
            {
                return _parentTask;
            }
            set
            {
                OnparentTaskChanging(value);
                ReportPropertyChanging("parentTask");
                _parentTask = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentTask");
                OnparentTaskChanged();
            }
        }
        private global::System.Int32 _parentTask;
        partial void OnparentTaskChanging(global::System.Int32 value);
        partial void OnparentTaskChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notes
        {
            get
            {
                return _notes;
            }
            set
            {
                OnnotesChanging(value);
                ReportPropertyChanging("notes");
                _notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notes");
                OnnotesChanged();
            }
        }
        private global::System.String _notes;
        partial void OnnotesChanging(global::System.String value);
        partial void OnnotesChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bdownDBModel", Name="devloper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class devloper : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new devloper object.
        /// </summary>
        /// <param name="developerId">Initial value of the developerId property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        public static devloper Createdevloper(global::System.Int32 developerId, global::System.String firstName)
        {
            devloper devloper = new devloper();
            devloper.developerId = developerId;
            devloper.firstName = firstName;
            return devloper;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 developerId
        {
            get
            {
                return _developerId;
            }
            set
            {
                if (_developerId != value)
                {
                    OndeveloperIdChanging(value);
                    ReportPropertyChanging("developerId");
                    _developerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("developerId");
                    OndeveloperIdChanged();
                }
            }
        }
        private global::System.Int32 _developerId;
        partial void OndeveloperIdChanging(global::System.Int32 value);
        partial void OndeveloperIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hoursPerDayAvailable
        {
            get
            {
                return _hoursPerDayAvailable;
            }
            set
            {
                OnhoursPerDayAvailableChanging(value);
                ReportPropertyChanging("hoursPerDayAvailable");
                _hoursPerDayAvailable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hoursPerDayAvailable");
                OnhoursPerDayAvailableChanged();
            }
        }
        private Nullable<global::System.Int32> _hoursPerDayAvailable;
        partial void OnhoursPerDayAvailableChanging(Nullable<global::System.Int32> value);
        partial void OnhoursPerDayAvailableChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bdownDBModel", Name="project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new project object.
        /// </summary>
        /// <param name="projectId">Initial value of the projectId property.</param>
        /// <param name="projectName">Initial value of the projectName property.</param>
        /// <param name="leadDeveloper">Initial value of the leadDeveloper property.</param>
        /// <param name="priority">Initial value of the priority property.</param>
        public static project Createproject(global::System.Int32 projectId, global::System.String projectName, global::System.Int32 leadDeveloper, global::System.Int32 priority)
        {
            project project = new project();
            project.projectId = projectId;
            project.projectName = projectName;
            project.leadDeveloper = leadDeveloper;
            project.priority = priority;
            return project;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 projectId
        {
            get
            {
                return _projectId;
            }
            set
            {
                if (_projectId != value)
                {
                    OnprojectIdChanging(value);
                    ReportPropertyChanging("projectId");
                    _projectId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("projectId");
                    OnprojectIdChanged();
                }
            }
        }
        private global::System.Int32 _projectId;
        partial void OnprojectIdChanging(global::System.Int32 value);
        partial void OnprojectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String projectName
        {
            get
            {
                return _projectName;
            }
            set
            {
                OnprojectNameChanging(value);
                ReportPropertyChanging("projectName");
                _projectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("projectName");
                OnprojectNameChanged();
            }
        }
        private global::System.String _projectName;
        partial void OnprojectNameChanging(global::System.String value);
        partial void OnprojectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 leadDeveloper
        {
            get
            {
                return _leadDeveloper;
            }
            set
            {
                OnleadDeveloperChanging(value);
                ReportPropertyChanging("leadDeveloper");
                _leadDeveloper = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("leadDeveloper");
                OnleadDeveloperChanged();
            }
        }
        private global::System.Int32 _leadDeveloper;
        partial void OnleadDeveloperChanging(global::System.Int32 value);
        partial void OnleadDeveloperChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 priority
        {
            get
            {
                return _priority;
            }
            set
            {
                OnpriorityChanging(value);
                ReportPropertyChanging("priority");
                _priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("priority");
                OnpriorityChanged();
            }
        }
        private global::System.Int32 _priority;
        partial void OnpriorityChanging(global::System.Int32 value);
        partial void OnpriorityChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bdownDBModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bdownDBModel", Name="task")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class task : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new task object.
        /// </summary>
        /// <param name="taskId">Initial value of the taskId property.</param>
        /// <param name="assignedTo">Initial value of the assignedTo property.</param>
        /// <param name="originalEstimatedHours">Initial value of the originalEstimatedHours property.</param>
        /// <param name="hoursSpentOnTask">Initial value of the hoursSpentOnTask property.</param>
        /// <param name="project_id">Initial value of the project_id property.</param>
        /// <param name="priority">Initial value of the priority property.</param>
        /// <param name="taskName">Initial value of the taskName property.</param>
        /// <param name="startDate">Initial value of the startDate property.</param>
        /// <param name="dueDate">Initial value of the dueDate property.</param>
        public static task Createtask(global::System.Int32 taskId, global::System.Int32 assignedTo, global::System.Int32 originalEstimatedHours, global::System.Int32 hoursSpentOnTask, global::System.Int32 project_id, global::System.Int32 priority, global::System.String taskName, global::System.DateTime startDate, global::System.DateTime dueDate)
        {
            task task = new task();
            task.taskId = taskId;
            task.assignedTo = assignedTo;
            task.originalEstimatedHours = originalEstimatedHours;
            task.hoursSpentOnTask = hoursSpentOnTask;
            task.project_id = project_id;
            task.priority = priority;
            task.taskName = taskName;
            task.startDate = startDate;
            task.dueDate = dueDate;
            return task;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 taskId
        {
            get
            {
                return _taskId;
            }
            set
            {
                if (_taskId != value)
                {
                    OntaskIdChanging(value);
                    ReportPropertyChanging("taskId");
                    _taskId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("taskId");
                    OntaskIdChanged();
                }
            }
        }
        private global::System.Int32 _taskId;
        partial void OntaskIdChanging(global::System.Int32 value);
        partial void OntaskIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 assignedTo
        {
            get
            {
                return _assignedTo;
            }
            set
            {
                OnassignedToChanging(value);
                ReportPropertyChanging("assignedTo");
                _assignedTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("assignedTo");
                OnassignedToChanged();
            }
        }
        private global::System.Int32 _assignedTo;
        partial void OnassignedToChanging(global::System.Int32 value);
        partial void OnassignedToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 originalEstimatedHours
        {
            get
            {
                return _originalEstimatedHours;
            }
            set
            {
                OnoriginalEstimatedHoursChanging(value);
                ReportPropertyChanging("originalEstimatedHours");
                _originalEstimatedHours = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("originalEstimatedHours");
                OnoriginalEstimatedHoursChanged();
            }
        }
        private global::System.Int32 _originalEstimatedHours;
        partial void OnoriginalEstimatedHoursChanging(global::System.Int32 value);
        partial void OnoriginalEstimatedHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hoursSpentOnTask
        {
            get
            {
                return _hoursSpentOnTask;
            }
            set
            {
                OnhoursSpentOnTaskChanging(value);
                ReportPropertyChanging("hoursSpentOnTask");
                _hoursSpentOnTask = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hoursSpentOnTask");
                OnhoursSpentOnTaskChanged();
            }
        }
        private global::System.Int32 _hoursSpentOnTask;
        partial void OnhoursSpentOnTaskChanging(global::System.Int32 value);
        partial void OnhoursSpentOnTaskChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 project_id
        {
            get
            {
                return _project_id;
            }
            set
            {
                Onproject_idChanging(value);
                ReportPropertyChanging("project_id");
                _project_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("project_id");
                Onproject_idChanged();
            }
        }
        private global::System.Int32 _project_id;
        partial void Onproject_idChanging(global::System.Int32 value);
        partial void Onproject_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> shareOfProject
        {
            get
            {
                return _shareOfProject;
            }
            set
            {
                OnshareOfProjectChanging(value);
                ReportPropertyChanging("shareOfProject");
                _shareOfProject = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("shareOfProject");
                OnshareOfProjectChanged();
            }
        }
        private Nullable<global::System.Int32> _shareOfProject;
        partial void OnshareOfProjectChanging(Nullable<global::System.Int32> value);
        partial void OnshareOfProjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> percentCompleted
        {
            get
            {
                return _percentCompleted;
            }
            set
            {
                OnpercentCompletedChanging(value);
                ReportPropertyChanging("percentCompleted");
                _percentCompleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("percentCompleted");
                OnpercentCompletedChanged();
            }
        }
        private Nullable<global::System.Int32> _percentCompleted;
        partial void OnpercentCompletedChanging(Nullable<global::System.Int32> value);
        partial void OnpercentCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 priority
        {
            get
            {
                return _priority;
            }
            set
            {
                OnpriorityChanging(value);
                ReportPropertyChanging("priority");
                _priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("priority");
                OnpriorityChanged();
            }
        }
        private global::System.Int32 _priority;
        partial void OnpriorityChanging(global::System.Int32 value);
        partial void OnpriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String taskName
        {
            get
            {
                return _taskName;
            }
            set
            {
                OntaskNameChanging(value);
                ReportPropertyChanging("taskName");
                _taskName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("taskName");
                OntaskNameChanged();
            }
        }
        private global::System.String _taskName;
        partial void OntaskNameChanging(global::System.String value);
        partial void OntaskNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime startDate
        {
            get
            {
                return _startDate;
            }
            set
            {
                OnstartDateChanging(value);
                ReportPropertyChanging("startDate");
                _startDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startDate");
                OnstartDateChanged();
            }
        }
        private global::System.DateTime _startDate;
        partial void OnstartDateChanging(global::System.DateTime value);
        partial void OnstartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dueDate
        {
            get
            {
                return _dueDate;
            }
            set
            {
                OndueDateChanging(value);
                ReportPropertyChanging("dueDate");
                _dueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dueDate");
                OndueDateChanged();
            }
        }
        private global::System.DateTime _dueDate;
        partial void OndueDateChanging(global::System.DateTime value);
        partial void OndueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hoursForTasksWithHigherPriority
        {
            get
            {
                return _hoursForTasksWithHigherPriority;
            }
            set
            {
                OnhoursForTasksWithHigherPriorityChanging(value);
                ReportPropertyChanging("hoursForTasksWithHigherPriority");
                _hoursForTasksWithHigherPriority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hoursForTasksWithHigherPriority");
                OnhoursForTasksWithHigherPriorityChanged();
            }
        }
        private Nullable<global::System.Int32> _hoursForTasksWithHigherPriority;
        partial void OnhoursForTasksWithHigherPriorityChanging(Nullable<global::System.Int32> value);
        partial void OnhoursForTasksWithHigherPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notes
        {
            get
            {
                return _notes;
            }
            set
            {
                OnnotesChanging(value);
                ReportPropertyChanging("notes");
                _notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notes");
                OnnotesChanged();
            }
        }
        private global::System.String _notes;
        partial void OnnotesChanging(global::System.String value);
        partial void OnnotesChanged();

        #endregion

    
    }

    #endregion

    
}
